version: 0.2

phases:
  build:
    commands:
      - packer build -color=false -var version_id=${CODEBUILD_SOURCE_VERSION} -var resolved_version_id=${CODEBUILD_RESOLVED_SOURCE_VERSION} -var build_id=${CODEBUILD_BUILD_ID} packer.json

artifacts:
  files:
    - manifest.json
    - test/**/*
