version: 0.2

phases:
  build:
    commands:
      - version_id=$(git describe --tags --always)
      - "[ -n \"$version_id\" ] || version_id=${CODEBUILD_SOURCE_VERSION}"
      - packer build -color=false -var version_id=${version_id} packer.json

artifacts:
  files:
    - manifest.json
    - test/**/*
